"""Add indexes on phone and foreign keys

Revision ID: 32d1d29e38f2
Revises: 763bf70d4f7c
Create Date: 2026-08-03 12:39:42.121185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d1d29e38f2'
down_revision: Union[str, Sequence[str], None] = '763bf70d4f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_employee_id'), 'bookings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_bookings_order_id'), 'bookings', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_service_id'), 'orders', ['service_id'], unique=False)
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_index(op.f('ix_orders_service_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_bookings_order_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_employee_id'), table_name='bookings')
    # ### end Alembic commands ###
